const TOTP_B32='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
let TOTP={secret:'',hashes:[],plain:[],started:false,confirmed:false};
function totpWarnActive(){return TOTP.started&&!TOTP.confirmed}
function totpCodesFile(){const s=t('totp.recovery_title')+' — Q Proxy\r\n\r\n';return s+TOTP.plain.join('\r\n')+'\r\n'}
function totpB32Encode(bytes){let s='',bits=0,acc=0;for(let i=0;i<bytes.length;i++){acc=(acc<<8)|bytes[i];bits+=8;while(bits>=5){bits-=5;s+=TOTP_B32[(acc>>>bits)&31]}}if(bits>0)s+=TOTP_B32[(acc<<(5-bits))&31];return s}
function totpB32Decode(str){const c=String(str||'').trim().toUpperCase().replace(/[\s-]+/g,'').replace(/=+$/,'');if(c.length<16||!/^[A-Z2-7]+$/.test(c))return null;const out=[];let bits=0,acc=0;for(const ch of c){acc=(acc<<5)|TOTP_B32.indexOf(ch);bits+=5;if(bits>=8){bits-=8;out.push((acc>>>bits)&255)}}return new Uint8Array(out)}
async function totpHotp(key,counter){const msg=new Uint8Array(8);let c=counter;for(let i=7;i>=0;i--){msg[i]=c%256;c=Math.floor(c/256)}const k=await crypto.subtle.importKey('raw',key,{name:'HMAC',hash:'SHA-1'},false,['sign']);const sig=new Uint8Array(await crypto.subtle.sign('HMAC',k,msg));const o=sig[sig.length-1]&15;const n=((sig[o]&127)<<24)|((sig[o+1]<<16))|((sig[o+2]<<8))|(sig[o+3]);return String(n%1000000).padStart(6,'0')}
async function totpCheck(secret,code){const key=totpB32Decode(secret);if(!key)return false;const norm=String(code||'').replace(/[\s-]+/g,'');if(!/^\d{6}$/.test(norm))return false;const ctr=Math.floor(Math.floor(Date.now()/1000)/30);for(let d=-1;d<=1;d++){if(ctr+d<0)continue;if(await totpHotp(key,ctr+d)===norm)return true}return false}
function totpIssuerUrl(secret){return 'otpauth://totp/'+encodeURIComponent('Q Proxy:admin')+'?secret='+encodeURIComponent(secret)+'&issuer='+encodeURIComponent('Q Proxy')+'&algorithm=SHA1&digits=6&period=30'}
function totpIdleHtml(){return '<div class="btn-row"><button type="button" class="btn btn--primary btn--sm" data-action="totp-start">'+esc(t('totp.setup'))+'</button><button type="button" class="btn btn--ghost btn--sm" data-action="totp-disable">'+esc(t('totp.disable'))+'</button></div>'+(totpWarnActive()?'<p class="field__hint" style="color:var(--warning)">'+esc(t('totp.warn.restart'))+'</p>':'')}
function totpCardHtml(){return '<section class="card"><div class="card__head"><div class="card__title">'+esc(t('totp.title'))+'</div></div><p class="field__hint">'+esc(t('totp.desc'))+'</p><p class="field__hint">'+esc(t('totp.status_hint'))+'</p><div id="totp-body">'+totpIdleHtml()+'</div></section>'}
function totpReset(){TOTP={secret:'',hashes:[],plain:[],started:false,confirmed:false};const b=$('totp-body');if(b)b.innerHTML=totpIdleHtml()}
function renderTotpSetup(){const b=$('totp-body');if(!b)return;b.innerHTML='<p class="field__hint">'+esc(t('totp.step_secret'))+'</p>'+'<div class="field__label-row"><span class="field__label">'+esc(t('totp.secret_label'))+'</span></div>'+'<div class="copy-field"><code id="totp-secret" dir="ltr">'+esc(TOTP.secret)+'</code><button type="button" class="btn btn--icon btn--sm" data-action="copy" data-copy-value="'+esc(TOTP.secret)+'" aria-label="'+esc(t('common.copy'))+'"><svg aria-hidden="true"><use href="#i-copy"/></svg></button><button type="button" class="btn btn--icon btn--sm" data-action="totp-qr" aria-label="'+esc(t('totp.show_qr'))+'"><svg aria-hidden="true"><use href="#i-qr"/></svg></button></div>'+(totpWarnActive()?'<p class="field__hint" style="color:var(--warning)">'+esc(t('totp.warn.restart'))+'</p>':'')+'<p class="field__hint">'+esc(t('totp.step_verify'))+'</p>'+'<div class="field" id="fw-totp-code"><div class="field__label-row"><label class="field__label" for="totp-code">'+esc(t('totp.code_label'))+'</label></div><input type="text" class="input input--mono" id="totp-code" autocomplete="one-time-code" inputmode="numeric" spellcheck="false" dir="ltr" maxlength="6"><p class="field__error"></p></div>'+'<p class="field__hint">'+esc(t('totp.step_backup'))+'</p>'+'<div class="field__label-row"><span class="field__label">'+esc(t('totp.recovery_title'))+'</span></div>'+'<div class="copy-field"><code id="totp-codes" dir="ltr">'+esc(TOTP.plain.join(' '))+'</code><button type="button" class="btn btn--icon btn--sm" data-action="copy" data-copy-value="'+esc(TOTP.plain.join('\n'))+'" aria-label="'+esc(t('common.copy'))+'"><svg aria-hidden="true"><use href="#i-copy"/></svg></button><button type="button" class="btn btn--icon btn--sm" data-action="totp-codes-download" aria-label="'+esc(t('totp.codes.download'))+'" title="'+esc(t('totp.codes.download'))+'"><svg aria-hidden="true"><use href="#i-download"/></svg></button></div>'+'<label class="switch"><input type="checkbox" id="totp-saved" data-totp-saved><span class="switch__track"><span class="switch__thumb"></span></span><span class="switch__label">'+esc(t('totp.saved.confirm'))+'</span></label>'+'<div class="btn-row"><button type="button" class="btn btn--primary btn--sm" data-action="totp-confirm" disabled>'+esc(t('totp.verify_enable'))+'</button><button type="button" class="btn btn--ghost btn--sm" data-action="totp-start">'+esc(t('totp.setup'))+'</button></div>'+'<p class="field__hint" style="color:var(--warning)">'+esc(t('totp.warn.clock'))+'</p>'}
function renderTotpDone(){const b=$('totp-body');if(!b)return;b.innerHTML='<p class="field__hint">'+esc(t('totp.enabled_ok'))+'</p>'+'<p class="field__hint" style="color:var(--warning)">'+esc(t('totp.warn.clock'))+'</p>'+'<div class="btn-row"><button type="button" class="btn btn--ghost btn--sm" data-action="totp-disable">'+esc(t('totp.disable'))+'</button></div>'}
